$(function(){
    $(".userindex").on('click',function(){
        $(location).attr('href','index.html');
    })
    $(".allgame").on('click',function(){
        $(location).attr('href','allGames.html');
    })
    $(".myinfo").on('click',function(){
        $(location).attr('href','personalInfo.html');
    })
    $(".aboutme").on('click',function(){
        $(location).attr('href','index.html');
    })
})